name: 友链整合🔗
on:
  workflow_dispatch:

jobs:
  merge-links:
    name: 友链整合🔗
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: 'npm install'
      - run: 'node index.js'
        env:
          ISSUE_BODY: ''
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git
        run: 'git config --global user.email "${{ secrets.EMAIL }}"; git config --global user.name "Mufanc"'
      - name: Commit changes
        run: 'git add .; git commit -m "Update by github actions"; git push origin master'